sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-053
env:
  global:
    -
      # LTD_AWS_ID
      secure: S94v6+R1m0F61GdNlPmT0E44k/zX2d+e9moumHc/JEnW05uI9epIN1pC41OzZCrQpgl7h+T2lhHTyH17PLT/Oo/8oy7bl6ufwe7uYlNKQGD/KtJmWVCBicdqwAG1MU5xZaQLdO4h3vFV+P2sOcXuqaEaPXLT7d3d9ZTv+zCyBjzynGkWbk/HLr7dzgZSp+uJYkxpvlgR8f+/x0qbnEL/CKavBkwo4EjBOWPtEo7NtgMDyXA7yYPxZW2tnYYkebvw5KDBlZlEnDG8GxXxNUcCJnBUyFtGJpbqP8ygNukxsB9amq4MYI4gxcQmjX0OqILT93ZUV+MupmQ+WDBabKTGYI//FUzeBYapSzYBZXGdKBcxjWfmuyyEx4dZDcWSsltheH3CA8xm3zPs8ZRyDvNpNNkgHXWbj7RXkjhq5cVjeWJu4v0YlaK3v3y1hGQhu2H0dzvB2+LP+qskuqheeaLodNHgclqX1haszaoyoWnBrXgeZpQcZ8ktorIrocPHJPnvd7vvXF9rbbP5l69cACfk2JZovfk868u1HErYFOHQORKlKBV6MhV5o0Y+2qlGC5PhYGttbuXbAciERhJ3lHOmW5vOGTvZL/V8seze2dNA3gW2x8pCGqAtzO8/evvn9Vty1kNloIXN4QmSvnWF7PFjBNRILmA94PAv2VOMCnt2q88=
    -
      # LTD_AWS_SECRET
      secure: aHuaaiiKVMX5H6lJbJmf5Oh6d/cYW1n3DAC7zk2ZKqNqdX9pRkCHny8VCMkelNHjzpJaiCbhP0HqKAAyh7lfqAtP6wPGgX8J0y1lcmoDwZNk4B0bNSY+Grnzc6adnpHslth/B3dtmog/UiUhk4+IcjmWLA0aP6ZXr2tHh6yzLhqCrYD+AWo37jfgEeNYdEXA9yeYSLTXPtLy3+tAexRLvJOT5v328vLQdl7TR5qdRgoOw9llw60INaOJqK30a0d2df4gnel08hCyzpOcskOw7wWdYz/IW3fhthqf19QTK01RONShD9XPbhaK+CEE7eHkim3MdIBnQ29LgGSlwmMURFVaIyVB0ciORS9T/IZhtmxoyltw6Q9eXvRsVsBRNqkj0am68DXjvwXJnKYslk1nHyhpL2QBJTZCbkKfhjm4uQRMB70I7GX9Wx746iUsBxQ5Aili/0QHKQktzjdSWxJ2XKq4Mcw4pJZAwVEzVqK03Uw5u05oF9HHDiuT1SNyahhyM60RlVbfihEFhbrW1Kh8aEiLZjgRiEsg5K3Za1v9s7aXxCNGbmHeC/VbFnSb2+niuFuihv9i5fLReYzuwGlQfkG1sChhqK0L4nnC7nMGg6OSoUdthLZq1vVV+g89NQBIIdciGohV6qpHgiVv0liwqMoJ0yBp1XOsUqARVQ8AH7g=
    -
      # LTD_USERNAME
      secure: mBgBloz8cEVXXMMpTOWgD73c+FudF2a+WbTHjcD3oX2+dDEvYxLu62IJ2DeWYzFXNux0MzW9nDfdaWcSjhykV2du8CA50XjfCs4eGuB4zApzWCac3Nfg5sZDw3M+xTwX+f7t0Gyie7Hak5Y30vfB6syIcFNqDwAzfmh0HlfELf9MM7P6Js4hK6iM+f1lc8a5npmWZ9NSNScAJfBIJqsfJFCGii4ePPwZabEbVj2PoQRIGqsTRQwSuHF/x/KFDOkf/GIpyJHSym+s9elnofkvnpXX6NFNuMt3MLs0ajSQQH5tEf9sySbatU3J4o7CxcepCXbAz5WaA6qwMh/UZ1rg/o3PL0/81s26RgwpQcqeT3TnVtBhRBlaslITDhV7aYZ8fmQmU31mICzApmU1bu22wvpU9tLVpUe1SZTaqQMJKzmMW5VM6WAG+2ICH0NMdOLayZrZHfmJEVIfZnB1U8OHgckEKOAkzT9lC7ySifdJ7z689sWN/kxP+3wFfpyo6AFuzvxGOFHdb1edKLYRJXvaogaWgj/MT16dfugIBQAEEjJg52FTJBVLSLRvycOo2x580Go/mSrUORgMhYN4owUXYsurpG4It33JDlxcWmKu8z1R4NUw+Tzf69LX+9c3Dw+oV0Oo7QP7joZJwKZhD+a4bIaRQyPuy7eNA3XduW2LRHg=
    -
      # LTD_PASSWORD
      secure: JcxcnFsnGPYnbOdrSulAUlEUxu/VbDzD5EZFWZQOQEnD8wPyGIhwy3/NQCHn1i7N9lANyLsSqOboMJqiDAKfgBnHlkPenF+cM4fsq2RpKaEfxIpFToWlh3qT/bzq2biKAPsv0E4DeHMeBdxq8VKCdDf/7FhCJ6Dajr0fzj8fTvGBIkLf2GJxggkBMoRpxtMXJf4KzOTNEyD7CG5iFcRkoAlbD64DW5n5XsHcACbL0ONEgOhneIOLmCBKzJHw5wTK+aJ8dlk4bUmSnH4m/ELd/OrlshLAgJW4jTb2DIoPUhtzsNSf0GyKVcxObJv5vj+qqNl+ozYswiHn+VcBdpIh3snTtScmrGOEdNkB/UCKgcNHODGHzo6WoIkdM7Z69UPR3Is4qy14Da4UXmG0ZKRwWrIPXVbdSyk3VIVdEI1sgBb7gDUzvV5yQdxDULZMsk5wJCcyLauVvHHGI4nI/YE0NBsJ+3lO2fWOXQW/YlRKUGyzzOngetHwDvjJCX4iLBGVKJ90D0uT2iTR30k2LaHNn8dK/FMNSXJV+LgDE4joBj3YFs0bfWEN/z+3IqhxtHt3YA8vOJu39ABAeHF5eItiHkvqLee4IWlfboUqNU/7czvcmRpOdtD3YshyGlE2TTk4Q3VCoJp0Gfvsi2F2q8YQUm0vT/CSnximel0byut3pmk=
